import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/shared/Header";


export const metadata: Metadata = {
  title: "Zed",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
